In [19]:
import requests
from bs4 import BeautifulSoup
import random
import pandas as pd
import re

In [20]:
title = "Data ML"
location = "Bagkok, Thailand"
start = 0  # Starting point for pagination

In [21]:
def split_criteria(criteria_array):
    criteria_dict = {}
    items = []
    for i in criteria_array:
        stripped = i.strip()
        if stripped != "":
            items.append(stripped)
    for index, item in enumerate(items):
        if index % 2 == 0:
            key = item
            value = items[index + 1]
            criteria_dict[key] = value
    return criteria_dict

In [22]:
# list_url = f"https://www.linkedin.com/jobs/search?keywords={title}&location={location}&pageNum=0".replace(" ", "%20")
list_url = f"https://www.linkedin.com/jobs-guest/jobs/api/seeMoreJobPostings/search?keywords={title}&location={location}&start=0".replace(" ", "%2B")
response = requests.get(list_url)

list_data = response.text
list_soup = BeautifulSoup(list_data, 'html.parser')
page_jobs = list_soup.find_all('li')

In [23]:
print(list_url)

https://www.linkedin.com/jobs-guest/jobs/api/seeMoreJobPostings/search?keywords=Data%2BML&location=Bagkok,%2BThailand&start=0

In [24]:
id_list = []
for job in page_jobs:
    base_card_div = job.find("div", {"class" : "base-card"})
    if base_card_div:
        # print(base_card_div)
        job_id = base_card_div.get("data-entity-urn", "").split(":")[-1]
        # print(f"Job ID: {job_id}")
        id_list.append(job_id)

# page_jobs[20].find("div", {"class" : "base-card"})

In [25]:
len(id_list)

10

In [26]:
print(f"https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/{id_list[1]}")

https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/4300405780

In [27]:
job_list = []
for job_id in id_list:
    job_url = f"https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/{job_id}"
    job_response = requests.get(job_url)
    job_post = {}
    job_soup = BeautifulSoup(job_response.text, 'html.parser')
    job_post['job_id'] = "li-" + job_id
    job_post['job_website'] = job_url.split(".")[1]
    job_post['job_url'] = job_url
    try:
        job_post['job_title'] = job_soup.find("h2", {"class" : "top-card-layout__title"}).text.strip()
    except:
        job_post['job_title'] = None
    try:
        job_post['company_name'] = job_soup.find("a", {"class": "topcard__org-name-link"}).text.strip()
    except:
        job_post['company_name'] = None
    try:
        job_post['company_url'] = job_soup.find("a", {"class": "topcard__org-name-link"})['href']
    except:
        job_post['company_url'] = None
    try:
        job_post['time_posted'] = job_soup.find("span", {"class" : "posted-time-ago__text"}).text.strip()
    except:
        job_post['time_posted'] = None
    try:
        job_post['num_applicants'] = job_soup.find("figcaption", {"class" : "num-applicants__caption"}).text.strip()
    except:
        try:
            job_post['num_applicants'] = job_soup.find("span", {"class" : "num-applicants__caption"}).text.strip()
        except:
            job_post['num_applicants'] = None
    try:
        job_post['location'] = job_soup.find("span", {"class" : "topcard__flavor topcard__flavor--bullet"}).text.strip()
    except:
        job_post['location'] = None
    try:
        job_criteria = job_soup.find("ul", {"class" : "description__job-criteria-list"}).text.strip().split("\n")
        criteria_dict = split_criteria(job_criteria)
        job_post['seniority_level'] = criteria_dict.get('Seniority level', None)
        job_post['employment_type'] = criteria_dict.get('Employment type', None)
        job_post['job_function'] = criteria_dict.get('Job function', None)
        job_post['industries'] = criteria_dict.get('Industries', None)
    except:
        job_post['seniority_level'] = None
        job_post['employment_type'] = None
        job_post['job_function'] = None
        job_post['industries'] = None
    try:
        description = job_soup.find("div", {"class" : "show-more-less-html__markup show-more-less-html__markup--clamp-after-5 relative overflow-hidden"})
        if description.find_all("strong"):
            for strong_tag in description.find_all("strong"):
                strong_tag.string = f"<strong>{strong_tag.text}</strong>"
        if description.find_all("ul"):
            for li_tag in description.find_all("li"):
                li_tag.string = f"<li>{li_tag.text}</li>"

        job_post['job_description'] = description.get_text(separator="\n").strip()
    except:
        job_post['job_description'] = None

    job_list.append(job_post)

In [28]:
job_list

[{'job_id': 'li-4262353945',
  'job_website': 'linkedin',
  'job_url': 'https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/4262353945',
  'job_title': 'Business Intelligence (Shopee) Fresh Graduate',
  'company_name': 'Shopee',
  'company_url': 'https://sg.linkedin.com/company/shopee?trk=public_jobs_topcard-org-name',
  'time_posted': '4 days ago',
  'num_applicants': 'Over 200 applicants',
  'location': 'Bangkok, Bangkok City, Thailand',
  'seniority_level': 'Mid-Senior level',
  'employment_type': 'Full-time',
  'job_function': 'Strategy/Planning, Analyst, and Consulting',
  'industries': 'Internet Marketplace Platforms and Technology, Information and Internet',
  'job_description': "<strong>Job Description</strong>\n<li>Developing reports, dashboards, analysis and some automations (will be generally with SQL, PYTHON, EXCEL, in-House tools)</li>\n<li>Assisting the various business units as a discussion partner to plan, strategise, and grow business by enabling data-driven decision-making</li>\n<li>Serving as in-consultant who simplifies complex terminologies into more understandable insights to our internal clients</li>\n<li>Producing actionable insights that will be used to support or devise new strategies</li>\n<strong>Requirements</strong>\n<li>Master's or bachelor's degree in quantitative fields or a relevant field (e.g. Data Science/Computer Science) of study</li>\n<li>1-3 years experience in Data Analyst field</li>\n<li>Experience using SQL languages for querying (Python is a plus)</li>\n<li>Experience working with multiple stakeholders across various divisions</li>\n<li>Ability to make inferences from data and devise an appropriate course of actions</li>\n<li>Time management to deliver deadlines</li>\n<li>Satisfactory understanding of English</li>\n<li>Comfortable working with large data sets and numbers</li>\n<li>Self-starter with a can-do attitude</li>"},
 {'job_id': 'li-4300405780',
  'job_website': 'linkedin',
  'job_url': 'https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/4300405780',
  'job_title': '[TH] Business Intelligence - Fresh Graduate',
  'company_name': 'Shopee',
  'company_url': 'https://sg.linkedin.com/company/shopee?trk=public_jobs_topcard-org-name',
  'time_posted': '2 weeks ago',
  'num_applicants': 'Over 200 applicants',
  'location': 'Bangkok, Bangkok City, Thailand',
  'seniority_level': 'Entry level',
  'employment_type': 'Full-time',
  'job_function': 'Strategy/Planning, Analyst, and Consulting',
  'industries': 'Internet Marketplace Platforms and Technology, Information and Internet',
  'job_description': "<strong>About The Team</strong>\nThe \n<strong>Business Intelligence (BI)</strong>\n department is vital for transforming raw data into actionable insights that drive strategic business decisions. BI teams engage in strategic collaboration and consulting, working with stakeholders to define problems and provide data-driven recommendations.\nThe department's core functions include \n<strong>data analysis and reporting</strong>\n, using tools like \n<strong>SQL, Python, and Excel</strong>\n to provide clear, business-focused reports. They also focus on \n<strong>operational and process optimization</strong>\n, developing tools and automation to improve efficiency. Additionally, they perform\n<strong> ecosystem monitoring and optimization</strong>\n by proactively analyzing key areas like customer and seller performance to facilitate high-impact business changes.\nBy integrating these functions, the BI department ensures the organization operates with data-informed precision, leading to improved efficiency and sustained growth.\n<strong>Job Description</strong>\n<li>Conduct analysis of internal and external data, utilizing SQL, Python, and Excel.</li>\n<li>Translate complex data analyses into accessible, business-focused reports to deliver actionable insights and recommendations to senior management.</li>\n<li>Develop, maintain, and automate dashboards, reports, and visualizations to support strategic decision-making.</li>\n<li>Serve as a consultant to cross-functional teams, collaborating to identify business challenges and enhance analytical capabilities.</li>\n<li>Review and optimize data systems and processes to ensure data integrity and operational efficiency.</li>\n<strong>Requirements</strong>\n<li>Bachelor's or Master's degree in a relevant field.</li>\n<li>Advanced proficiency in SQL and Excel (Python is a plus)</li>\n<li>Fresh Graduate is preferred</li>\n<li>Fluency in English.</li>\n<strong>Submitting your resume today will ensure you're among the first to be notified when a suitable opportunity arises.</strong>"},
 {'job_id': 'li-4324559451',
  'job_website': 'linkedin',
  'job_url': 'https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/4324559451',
  'job_title': 'Junior Business Analytics (ShopeePay)',
  'company_name': 'Shopee',
  'company_url': 'https://sg.linkedin.com/company/shopee?trk=public_jobs_topcard-org-name',
  'time_posted': '5 days ago',
  'num_applicants': '182 applicants',
  'location': 'Bangkok, Bangkok City, Thailand',
  'seniority_level': 'Entry level',
  'employment_type': 'Full-time',
  'job_function': 'Business Development and Marketing',
  'industries': 'Financial Services',
  'job_description': '<strong>Job Description</strong>\nJob Description:\n<li>Manage end-to-end marketing initiatives such as CRM to drive new user acquisition and retention, including mechanics planning, budget optimization, user segment breakdown, A/B testing and performance analysis</li>\n<li>Provide details plans for marketing campaigns or A/B testings, aligning them with the overall business objectives </li>\n<li>Regularly review and analyze key marketing metrics to provide insights that guide decision-making for campaign improvement</li>\n<li>Conduct data-driven analysis to provide actionable insights and recommendations for current business direction on ShopeePay, Digital Products and Credit businesses</li>\n<li>Design analysis framework, extract relevant data, run in-depth analysis, and deliver findings using suitable visualization and reporting tools to communicate and collaborate with related stakeholders </li>\n<li>Support other special projects as requested</li>\n<strong>Requirements</strong>\nRequirements:\n<li>At least 1 - 2 years of work experiences in areas of marketing analytics, business analytics, data analytics, strategy consulting, e-commerce or tech industries</li>\n<li>Strong technical skills with experience in SQL is a must</li>\n<li>Intermediate MS Excel and Google Sheet skills, capable of utilizing different formulas and features to drive desired result</li>\n<li>Strong analytical and logical reasoning skills</li>\n<li>Strong sense of ownership over their work and long-term goals; a self-starter</li>\n<li>Excellent communication skills in both written and verbal format in Thai and English</li>\n<li>Reliable and good team player who enjoys a fast-paced and iterative environment</li>'},
 {'job_id': 'li-4277459478',
  'job_website': 'linkedin',
  'job_url': 'https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/4277459478',
  'job_title': 'Junior Marketing Analytics (ShopeePay)',
  'company_name': 'Shopee',
  'company_url': 'https://sg.linkedin.com/company/shopee?trk=public_jobs_topcard-org-name',
  'time_posted': '7 hours ago',
  'num_applicants': 'Over 200 applicants',
  'location': 'Bangkok, Bangkok City, Thailand',
  'seniority_level': 'Entry level',
  'employment_type': 'Full-time',
  'job_function': 'Business Development and Marketing',
  'industries': 'Financial Services',
  'job_description': '<strong>Job Description</strong>\n<li>Manage end-to-end marketing initiatives such as CRM to drive new user acquisition and retention, including mechanics planning, budget optimization, user segment breakdown, testing and performance analysis</li>\n<li>Regularly review and analyze key marketing metrics to provide insights that guide decision-making for campaign improvement</li>\n<li>Conduct data-driven analysis to provide actionable insights and recommendations for current business direction on ShopeePay, Digital Products and Credit businesses</li>\n<li>Design analysis framework, extract relevant data, run in-depth analysis, and deliver findings using suitable visualization and reporting tools to communicate and collaborate with related stakeholders </li>\n<li>Support other special projects as requested</li>\n<strong>Requirements</strong>\n<li>At least 1 - 2 years of work experiences in areas of marketing analytics, business analytics, data analytics, strategy consulting, e-commerce or tech industries</li>\n<li>Strong technical skills with experience in SQL is a must</li>\n<li>Intermediate MS Excel and Google Sheet skills, capable of utilizing different formulas and features to drive desired result</li>\n<li>Strong analytical and logical reasoning skills</li>\n<li>Strong sense of ownership over their work and long-term goals; a self-starter</li>\n<li>Excellent communication skills in both written and verbal format in Thai and English</li>\n<li>Reliable and good team player who enjoys a fast-paced and iterative environment</li>'},
 {'job_id': 'li-4289428380',
  'job_website': 'linkedin',
  'job_url': 'https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/4289428380',
  'job_title': 'Junior Business Analyst/Product Management (ShopeePay)',
  'company_name': 'Shopee',
  'company_url': 'https://sg.linkedin.com/company/shopee?trk=public_jobs_topcard-org-name',
  'time_posted': '2 weeks ago',
  'num_applicants': 'Over 200 applicants',
  'location': 'Bangkok, Bangkok City, Thailand',
  'seniority_level': 'Entry level',
  'employment_type': 'Full-time',
  'job_function': 'Project Management, Strategy/Planning, and Product Management',
  'industries': 'Financial Services',
  'job_description': '<strong>Job Description</strong>\n<li>Gather and develop business requirements; construct workflow diagrams and technical documentation; communicate product features; review BRD / PRD as required by business requirements</li>\n<li>Understand and translate customer needs into business and technology solutions, provide consultation of payment services, functional, application designs and ensure technology and business solutions represent business requirements</li>\n<li>Analyze, support and develop the feasibility of requirements, project plans, schedules including integration process for new systems and enhancements to existing systems; ensures the system design meets business requirements</li>\n<li>Manage all change requests, keep track of the timeline, validate all schedule impacts, and communicate changes to all teams</li>\n<li>Work cross-functionally with our stakeholders, business and technology teams to ensure timely and quality release of product / enhancements</li>\n<li>Monitor project progress by tracking activities; resolving issues; recommending actions to ensure timely completion</li>\n<strong>Requirements</strong>\n<li>Minimum 1 year of experience as a Product Manager or Business Analyst in Banking platform, E-wallet, or IT solution industry</li>\n<li>Proficient in working with numbers and data organization</li>\n<li>Results and detail-oriented, with strong intuitions on how to solve problems creatively and quickly</li>\n<li>Strong ability to grasp technical concepts and simplify them for clear communication skills</li>\n<li>Ability to work independently in a fast-paced environment</li>\n<li>Ability to speak and write in English</li>\n<li>Strong knowledge of payment services background is a plus</li>'},
 {'job_id': 'li-4368094924',
  'job_website': 'linkedin',
  'job_url': 'https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/4368094924',
  'job_title': 'Finance Operations - Reconciliation (ShopeePay)',
  'company_name': 'Shopee',
  'company_url': 'https://sg.linkedin.com/company/shopee?trk=public_jobs_topcard-org-name',
  'time_posted': '2 days ago',
  'num_applicants': '37 applicants',
  'location': 'Bangkok, Bangkok City, Thailand',
  'seniority_level': 'Entry level',
  'employment_type': 'Full-time',
  'job_function': 'Other',
  'industries': 'Financial Services',
  'job_description': "<strong>Job Description</strong>\n<li>Perform financial reconciliations for transactions from various sources</li>\n<li>Collect payment supporting documents to support the report</li>\n<li>Analyze, interpret and investigate data discrepancies in a methodological approach</li>\n<li>Be proactive in identifying issues, recognizing the patterns of a problem and collaborate with other teams to provide short/medium/long term solutions</li>\n<li>Contribute to design new and enhance existing programs and processes in order to ensure the accuracy of data</li>\n<li>Respond to constant changes from different business demands and be able to understand how daily tasks need to be adjusted according to these changes</li>\n<li>Ad-hoc data preparation or reconciliation</li>\n<strong>Requirements</strong>\n<li>Bachelor's degree in Finance, Business, or any related field. Fresh graduates are welcome to apply</li>\n<li>Good Command of English both speaking and writing</li>\n<li>Proficient in MS Excel, MS Office and Google Sheets.</li>\n<li>Strong attention to detail and ability to work under time-sensitive deadlines</li>\n<li>Ability to work both independently and as part of a team</li>\n<li>Good attitude in working with stakeholders in various functions</li>\n<li>High level of integrity and work ethic; capable of managing confidential data with professionalism</li>"},
 {'job_id': 'li-4241154712',
  'job_website': 'linkedin',
  'job_url': 'https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/4241154712',
  'job_title': 'Project Management Executive (Shopee)',
  'company_name': 'Shopee',
  'company_url': 'https://sg.linkedin.com/company/shopee?trk=public_jobs_topcard-org-name',
  'time_posted': '1 week ago',
  'num_applicants': 'Over 200 applicants',
  'location': 'Bangkok, Bangkok City, Thailand',
  'seniority_level': 'Entry level',
  'employment_type': 'Full-time',
  'job_function': 'Sales, Business Development, and Strategy/Planning',
  'industries': 'Internet Marketplace Platforms and Technology, Information and Internet',
  'job_description': '<strong>About The Team</strong>\nAs part of Shopee Regional Business Development team, you will play a key role in driving the growth of our business across the region. You will collaborate with partners across markets, as well as cross-functional stakeholders, and make meaningful impacts.\n<strong>Job Description</strong>\n<li>Assist in driving strategic initiatives (project-based role) across different markets and achieving business impact in growth, profitability, and efficiency.</li>\n<li>Learn and contribute to the overall strategy while gaining valuable experience.</li>\n<li>Work closely with local markets to identify opportunities and gaps, review problem statements, and generate useful solutions on regional strategic initiatives.</li>\n<li>Support data analysis and competitor benchmarking, take a hypothesis-driven approach to address business. challenges, identify new growth opportunities and initiate the project with a structured business case.</li>\n<strong>Requirements</strong>\n<li>1-3 years of experience working</li>\n<li>Previous experience management consulting or e-commerce industry would be preferred.</li>\n<li>Strong business acumen, critical thinking and ability to form actionable insights and recommendations using analytic skills.</li>\n<li>Strong project management, stakeholder management and communication skills.</li>\n<li>Team player, humble, organized and results driven.</li>\n<li>Able to work in fast-paced and dynamic environment.</li>'},
 {'job_id': 'li-4277459479',
  'job_website': 'linkedin',
  'job_url': 'https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/4277459479',
  'job_title': 'Business Intelligence (Data Analytics) (ShopeePay)',
  'company_name': 'Shopee',
  'company_url': 'https://sg.linkedin.com/company/shopee?trk=public_jobs_topcard-org-name',
  'time_posted': '2 weeks ago',
  'num_applicants': 'Over 200 applicants',
  'location': 'Bangkok, Bangkok City, Thailand',
  'seniority_level': 'Entry level',
  'employment_type': 'Full-time',
  'job_function': 'Strategy/Planning, Analyst, and Consulting',
  'industries': 'Financial Services',
  'job_description': "<strong>Job Description</strong>\n<li>Gather requirements and refine scope for data requests/projects from business users and management</li>\n<li>Create comprehensive SQL queries to generate and conduct reports/dashboards for ad hoc requests from different business units</li>\n<li>Develop and maintain ETLs for automatic reports and dashboards on the in-house data platform</li>\n<li>Collaborate with relevant local and regional teams on data acquisition, alignment of business logic/definitions, and functional updates</li>\n<li>Analyze quantitative data using statistical techniques and provide actionable insights to inform decisions/strategies</li>\n<li>Work closely with business users in rolling out consumer campaigns with data and analysis support</li>\n<strong>Requirements</strong>\n<li>Bachelor's/Master's degree, preferably in Analytics, Statistics, Computer Science or Engineering</li>\n<li>At least 1-2 years of experience in an Analytics, Business Intelligence or Data Engineer role with large, complex, high velocity data is preferred</li>\n<li>Strong foundation in data query/manipulation using SQL and data visualization</li>\n<li>Capable of making impactful contributions both as an individual and as a member of a team</li>\n<li>Able to switch hats between data/technical speak and business/layperson speak</li>\n<li>Strong analytical and problem-solving skills – possesses a relentless need for investigation and data exploration</li>\n<li>Results-oriented with a keen eye for detail and ability to solve problems creatively and quickly</li>\n<strong>It’s Great If You Have</strong>\n<li>Fluency in English</li>\n<li>Experience in e-commerce or digital payment platforms </li>\n<li>A global outlook and exposure to work with people from different cultures</li>\n<li>Python/JAVA or similar programming background</li>"},
 {'job_id': 'li-4367223564',
  'job_website': 'linkedin',
  'job_url': 'https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/4367223564',
  'job_title': 'Data Scientist',
  'company_name': 'AXONS',
  'company_url': 'https://th.linkedin.com/company/axonstech?trk=public_jobs_topcard-org-name',
  'time_posted': '6 days ago',
  'num_applicants': '73 applicants',
  'location': 'Bangkok, Bangkok City, Thailand',
  'seniority_level': 'Mid-Senior level',
  'employment_type': 'Full-time',
  'job_function': 'Information Technology',
  'industries': 'Technology, Information and Media',

In [29]:
# do dataframe stuff
df = pd.DataFrame(job_list)
df.head()

,job_id,job_website,job_url,job_title,company_name,company_url,time_posted,num_applicants,location,seniority_level,employment_type,job_function,industries,job_description
0,li-4262353945,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Business Intelligence (Shopee) Fresh Graduate,Shopee,https://sg.linkedin.com/company/shopee?trk=pub...,4 days ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,Full-time,"Strategy/Planning, Analyst, and Consulting","Internet Marketplace Platforms and Technology,...",<strong>Job Description</strong>\n<li>Developi...
1,li-4300405780,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,[TH] Business Intelligence - Fresh Graduate,Shopee,https://sg.linkedin.com/company/shopee?trk=pub...,2 weeks ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,"Strategy/Planning, Analyst, and Consulting","Internet Marketplace Platforms and Technology,...",<strong>About The Team</strong>\nThe \n<strong...
2,li-4324559451,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Junior Business Analytics (ShopeePay),Shopee,https://sg.linkedin.com/company/shopee?trk=pub...,5 days ago,182 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,Business Development and Marketing,Financial Services,<strong>Job Description</strong>\nJob Descript...
3,li-4277459478,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Junior Marketing Analytics (ShopeePay),Shopee,https://sg.linkedin.com/company/shopee?trk=pub...,7 hours ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,Business Development and Marketing,Financial Services,<strong>Job Description</strong>\n<li>Manage e...
4,li-4289428380,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Junior Business Analyst/Product Management (Sh...,Shopee,https://sg.linkedin.com/company/shopee?trk=pub...,2 weeks ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,"Project Management, Strategy/Planning, and Pro...",Financial Services,<strong>Job Description</strong>\n<li>Gather a...

In [30]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
from datetime import datetime

def split_criteria(criteria_array):
    criteria_dict = {}
    items = []
    for i in criteria_array:
        stripped = i.strip()
        if stripped != "":
            items.append(stripped)
    for index, item in enumerate(items):
        if index % 2 == 0:
            key = item
            value = items[index + 1]
            criteria_dict[key] = value
    return criteria_dict

def request_preview_job_posting(title, location, i):
    list_url = f"https://www.linkedin.com/jobs-guest/jobs/api/seeMoreJobPostings/search?keywords={title}&location={location}&start={i}".replace(" ", "%2B")
    try:
        response = requests.get(list_url)
    except:
        # sleep
        try:
            time.sleep(5)
            response = requests.get(list_url)
        except requests.exceptions.RequestException as e:
            print(f"Failed to retrieve data from {list_url}: {e}")
            return None
    list_data = response.text
    list_soup = BeautifulSoup(list_data, 'html.parser')
    page_jobs = list_soup.find_all('li')
    return page_jobs

def extract_job_ids(page_jobs):
    id_list = []
    for job in page_jobs:
        base_card_div = job.find("div", {"class" : "base-card"})
        if base_card_div:
            # print(base_card_div)
            job_id = base_card_div.get("data-entity-urn", "").split(":")[-1]
                # print(f"Job ID: {job_id}")
            id_list.append(job_id)
    return id_list

def scrape_job_posts(id_list):
    job_list = []
    for job_id in id_list:
        job_url = f"https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/{job_id}"
        job_response = requests.get(job_url)
        job_post = {}
        job_soup = BeautifulSoup(job_response.text, 'html.parser')
        job_post['job_id'] = "li-" + job_id
        job_post['job_website'] = job_url.split(".")[1]
        job_post['job_url'] = job_url
        try:
            job_post['job_title'] = job_soup.find("h2", {"class" : "top-card-layout__title"}).text.strip()
        except:
            job_post['job_title'] = None
        try:
            job_post['company_name'] = job_soup.find("a", {"class": "topcard__org-name-link"}).text.strip()
        except:
            job_post['company_name'] = None
        try:
            job_post['company_url'] = job_soup.find("a", {"class": "topcard__org-name-link"})['href']
        except:
            job_post['company_url'] = None
        try:
            job_post['time_posted'] = job_soup.find("span", {"class" : "posted-time-ago__text"}).text.strip()
        except:
            job_post['time_posted'] = None
        try:
            job_post['num_applicants'] = job_soup.find("figcaption", {"class" : "num-applicants__caption"}).text.strip()
        except:
            try:
                job_post['num_applicants'] = job_soup.find("span", {"class" : "num-applicants__caption"}).text.strip()
            except:
                job_post['num_applicants'] = None
        try:
            job_post['location'] = job_soup.find("span", {"class" : "topcard__flavor topcard__flavor--bullet"}).text.strip()
        except:
            job_post['location'] = None
        try:
            job_criteria = job_soup.find("ul", {"class" : "description__job-criteria-list"}).text.strip().split("\n")
            criteria_dict = split_criteria(job_criteria)
            job_post['seniority_level'] = criteria_dict.get('Seniority level', None)
            job_post['employment_type'] = criteria_dict.get('Employment type', None)
            job_post['job_function'] = criteria_dict.get('Job function', None)
            job_post['industries'] = criteria_dict.get('Industries', None)
        except:
            job_post['experience_level'] = None
        try:
            description = job_soup.find("div", {"class" : "show-more-less-html__markup show-more-less-html__markup--clamp-after-5 relative overflow-hidden"})
            if description.find_all("strong"):
                for strong_tag in description.find_all("strong"):
                    strong_tag.string = f"<strong>{strong_tag.text}</strong>"
            if description.find_all("ul"):
                for li_tag in description.find_all("li"):
                    li_tag.string = f"<li>{li_tag.text}</li>"

            job_post['job_description'] = description.get_text(separator="\n").strip()
        except:
            job_post['job_description'] = None

        job_list.append(job_post)
    return job_list



# create main function (__main__ )
if __name__ == "__main__":
    now = datetime.now()
    timestamp = now.strftime("%Y-%m-%dT%H%M%S")

    title = "Data ML"
    location = "Bagkok, Thailand"
    job_list_all = []
    for i in range(0, 1000, 25):
        page_jobs = request_preview_job_posting(title, location, i)
        if page_jobs is None:
            break
        id_list = extract_job_ids(page_jobs)
        job_list = (scrape_job_posts(id_list))
        job_list_all.extend(job_list)
        print(f"Scraped {len(job_list_all)} job posts so far...")
        print(f"This is page starting at {i}")

    df = pd.DataFrame(job_list_all)
    #save to csv
    # df.to_csv(f"./raw/linkedin/{timestamp}.csv", index=False)
    # save ib json
    # df.to_json(f"./raw/linkedin/{timestamp}.json", orient="records", lines=True)

Scraped 10 job posts so far...
This is page starting at 0
Scraped 20 job posts so far...
This is page starting at 25
Scraped 30 job posts so far...
This is page starting at 50
Scraped 40 job posts so far...
This is page starting at 75
Scraped 50 job posts so far...
This is page starting at 100
Scraped 60 job posts so far...
This is page starting at 125
Scraped 70 job posts so far...
This is page starting at 150
Scraped 80 job posts so far...
This is page starting at 175
Scraped 90 job posts so far...
This is page starting at 200
Scraped 100 job posts so far...
This is page starting at 225
Scraped 110 job posts so far...
This is page starting at 250
Scraped 120 job posts so far...
This is page starting at 275
Scraped 130 job posts so far...
This is page starting at 300
Scraped 140 job posts so far...
This is page starting at 325
Scraped 150 job posts so far...
This is page starting at 350
Scraped 160 job posts so far...
This is page starting at 375
Scraped 170 job posts so far...
This is page starting at 400
Scraped 180 job posts so far...
This is page starting at 425
Scraped 190 job posts so far...
This is page starting at 450
Scraped 200 job posts so far...
This is page starting at 475
Scraped 210 job posts so far...
This is page starting at 500
Scraped 220 job posts so far...
This is page starting at 525
Scraped 220 job posts so far...
This is page starting at 550
Scraped 230 job posts so far...
This is page starting at 575
Scraped 240 job posts so far...
This is page starting at 600
Scraped 250 job posts so far...
This is page starting at 625
Scraped 260 job posts so far...
This is page starting at 650
Scraped 270 job posts so far...
This is page starting at 675
Scraped 280 job posts so far...
This is page starting at 700
Scraped 290 job posts so far...
This is page starting at 725
Scraped 300 job posts so far...
This is page starting at 750
Scraped 310 job posts so far...
This is page starting at 775
Scraped 320 job posts so far...
This is page starting at 800
Scraped 330 job posts so far...
This is page starting at 825
Scraped 340 job posts so far...
This is page starting at 850
Scraped 340 job posts so far...
This is page starting at 875
Scraped 350 job posts so far...
This is page starting at 900
Scraped 360 job posts so far...
This is page starting at 925
Scraped 370 job posts so far...
This is page starting at 950
Scraped 380 job posts so far...
This is page starting at 975

In [34]:
df

,job_id,job_website,job_url,job_title,company_name,company_url,time_posted,num_applicants,location,seniority_level,employment_type,job_function,industries,job_description,experience_level
0,li-4262353945,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Business Intelligence (Shopee) Fresh Graduate,Shopee,https://sg.linkedin.com/company/shopee?trk=pub...,4 days ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,Full-time,"Strategy/Planning, Analyst, and Consulting","Internet Marketplace Platforms and Technology,...",<strong>Job Description</strong>\n<li>Developi...,NaN
1,li-4300405780,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,[TH] Business Intelligence - Fresh Graduate,Shopee,https://sg.linkedin.com/company/shopee?trk=pub...,2 weeks ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,"Strategy/Planning, Analyst, and Consulting","Internet Marketplace Platforms and Technology,...",<strong>About The Team</strong>\nThe \n<strong...,NaN
2,li-4324559451,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Junior Business Analytics (ShopeePay),Shopee,https://sg.linkedin.com/company/shopee?trk=pub...,5 days ago,184 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,Business Development and Marketing,Financial Services,<strong>Job Description</strong>\nJob Descript...,NaN
3,li-4277459478,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Junior Marketing Analytics (ShopeePay),Shopee,https://sg.linkedin.com/company/shopee?trk=pub...,7 hours ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,Business Development and Marketing,Financial Services,<strong>Job Description</strong>\n<li>Manage e...,NaN
4,li-4289428380,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Junior Business Analyst/Product Management (Sh...,Shopee,https://sg.linkedin.com/company/shopee?trk=pub...,2 weeks ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,"Project Management, Strategy/Planning, and Pro...",Financial Services,<strong>Job Description</strong>\n<li>Gather a...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,li-4321524600,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Project Engineer,Filtrona,https://sg.linkedin.com/company/filtrona?trk=p...,1 week ago,116 applicants,"Bangkok City, Thailand",Mid-Senior level,Full-time,"Manufacturing, Analyst, and Project Management","Manufacturing, Industrial Machinery Manufactur...",<strong>Who We Are:</strong>\nFiltrona is the ...,NaN
376,li-4352583225,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Category Demand Planning Manager,Beiersdorf,https://de.linkedin.com/company/beiersdorf?trk...,3 days ago,167 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,Full-time,Management and Manufacturing,Personal Care Product Manufacturing,"Your Tasks\n<li> Developing accurate, high qua...",NaN
377,li-4366681675,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Sr. Medical Science Liaison,Bayer,https://de.linkedin.com/company/bayer?trk=publ...,1 week ago,28 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,Full-time,Research and Health Care Provider,"Pharmaceutical Manufacturing, Biotechnology Re...",<strong>Major Tasks </strong>\n<li>Exchange an...,NaN
378,li-4366418621,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Regional Strategic Accounts Lead(GSKA-EL),Lazada,https://sg.linkedin.com/company/lazada?trk=pub...,1 week ago,73 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,Full-time,"Business Development, Project Management, and ...",Internet Marketplace Platforms and IT Services...,The Regional Strategic Account Lead role is re...,NaN
379,li-4360761918,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Vice President - Merchandising (Budget Control...,King Power,https://th.linkedin.com/company/kingpower?trk=...,3 weeks ago,140 applicants,"Bangkok City, Thailand",Director,Full-time,"Product Management, Finance, and Analyst",Retail Luxury Goods and Jewelry and Retail,<strong>Job Summary:</strong>\nThe Vice Presid...,NaN

In [36]:
df['job_title'].value_counts()

job_title
Data Engineer                                                       7
AI Engineer                                                         4
Business Analyst                                                    3
Marketing Manager                                                   3
Media Planner                                                       3
                                                                   ..
Data Scientist, KYC Anti Fraud                                      1
เจ้าหน้าที่วิเคราะห์ข้อมูล (Data Analysis Statistic)                1
Shopee's Future Operations Leaders Program (FLP) 2026 (Thailand)    1
eRTM Marketing Strategy Support Manager                             1
Vice President - Merchandising (Budget Control & Report)            1
Name: count, Length: 328, dtype: int64

In [37]:
# import linkedin job posts from csv
df_check = pd.read_csv("../raw/linkedin/2026-02-06T015239.csv")

In [40]:
# check duplicate df_check and df by join and check uqinue
df_check.merge(df, on='job_id', how='inner')

,job_id,job_website_x,job_url_x,job_title_x,company_name_x,company_url_x,time_posted_x,num_applicants_x,location_x,seniority_level_x,...,company_url_y,time_posted_y,num_applicants_y,location_y,seniority_level_y,employment_type_y,job_function_y,industries_y,job_description_y,experience_level_y
0,li-4262353945,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Business Intelligence (Shopee) Fresh Graduate,Shopee,https://sg.linkedin.com/company/shopee?trk=pub...,4 days ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,...,https://sg.linkedin.com/company/shopee?trk=pub...,4 days ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,Full-time,"Strategy/Planning, Analyst, and Consulting","Internet Marketplace Platforms and Technology,...",<strong>Job Description</strong>\n<li>Developi...,NaN
1,li-4300405780,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,[TH] Business Intelligence - Fresh Graduate,Shopee,https://sg.linkedin.com/company/shopee?trk=pub...,2 weeks ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Entry level,...,https://sg.linkedin.com/company/shopee?trk=pub...,2 weeks ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,"Strategy/Planning, Analyst, and Consulting","Internet Marketplace Platforms and Technology,...",<strong>About The Team</strong>\nThe \n<strong...,NaN
2,li-4369104006,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Data Engineer,OxygenAI,https://th.linkedin.com/company/oxygenai?trk=p...,NaN,Be among the first 25 applicants,Bangkok Metropolitan Area,Entry level,...,https://th.linkedin.com/company/oxygenai?trk=p...,7 hours ago,Be among the first 25 applicants,Bangkok Metropolitan Area,Entry level,Full-time,Information Technology,Software Development,<strong>Responsibilities:</strong>\n<li>Design...,NaN
3,li-4198762497,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Data Engineer,"Locus Telecommunication Inc., Ltd.",https://th.linkedin.com/company/locus-telecomm...,10 months ago,112 applicants,"Bangkok, Bangkok City, Thailand",Entry level,...,https://th.linkedin.com/company/locus-telecomm...,10 months ago,112 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,Information Technology,Software Development,<strong>Job Description</strong>\n<li>Work on ...,NaN
4,li-4321427106,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Data Engineer (IT),DHL eCommerce,https://de.linkedin.com/company/dhlecommerce?t...,1 week ago,76 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,...,https://de.linkedin.com/company/dhlecommerce?t...,1 week ago,76 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,Full-time,Information Technology,Truck Transportation,Welcome to DHL eCommerce!\nWe are excited to a...,NaN
5,li-4367838440,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Data Engineer,Inteltion,https://th.linkedin.com/company/inteltion?trk=...,3 days ago,83 applicants,"Bangkok, Bangkok City, Thailand",Entry level,...,https://th.linkedin.com/company/inteltion?trk=...,3 days ago,83 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,Information Technology,IT Services and IT Consulting,<strong>About the Company</strong>\nAt Intelti...,NaN
6,li-4324559451,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Junior Business Analytics (ShopeePay),Shopee,https://sg.linkedin.com/company/shopee?trk=pub...,5 days ago,183 applicants,"Bangkok, Bangkok City, Thailand",Entry level,...,https://sg.linkedin.com/company/shopee?trk=pub...,5 days ago,184 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,Business Development and Marketing,Financial Services,<strong>Job Description</strong>\nJob Descript...,NaN
7,li-4340303441,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,AI Engineer and Data Specialist,ooca - อูก้า แอปฯจิตวิทยา,https://th.linkedin.com/company/ooca?trk=publi...,2 months ago,Be among the first 25 applicants,"Bangkok, Bangkok City, Thailand",Entry level,...,https://th.linkedin.com/company/ooca?trk=publi...,2 months ago,Be among the first 25 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,Information Technology,IT Services and IT Consulting,<strong>Key Responsibilities</strong>\n<li>Des...,NaN
8,li-4354932951,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Data Analyst,The Mall Group,https://th.linkedin.com/company/the-mall-group...,3 weeks ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,...,https://th.linkedin.com/company/the-mall-group...,3 weeks ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,Full-time,"Marketing, Business Development, and Analyst","Retail, Market Research, and Food and Beverage...",<strong>Job Responsibilities:</strong>\n<li>Ex...,NaN
9,li-4354871933,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Data Analyst (Catalog Solutions),TecAlliance,https://de.linkedin.com/company/tecalliance?tr...,3 weeks ago,69 applicants,"Bangkok, Bangkok City, Thailand",Entry level,...,https://de.linkedin.com/company/tecalliance?tr...,3 weeks ago,70 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,Information Technology,Information Technology & Services,About the role:\nWe are looking for a passiona...,NaN
10,li-4367902312,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Business Data Analyst,CDG Group,https://th.linkedin.com/company/cdg-group-thai...,5 days ago,95 applicants,"Bangkok, Bangkok City, Thailand",Associate,...,https://th.linkedin.com/company/cdg-group-thai...,5 days ago,95 applicants,"Bangkok, Bangkok City, Thailand",Associate,Full-time,"Business Development, Analyst, and Information...","IT Services and IT Consulting, Software Develo...","<strong>Responsibilities:</strong>\n<li>Plan, ...",NaN
11,li-4360489522,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Data Analyst (MIS),ttb bank,https://th.linkedin.com/company/ttbbankofficia...,2 weeks ago,173 applicants,"Bangkok City, Thailand",Mid-Senior level,...,https://th.linkedin.com/company/ttbbankofficia...,2 weeks ago,174 applicants,"Bangkok City, Thailand",Mid-Senior level,Full-time,Information Technology and Analyst,Banking and Financial Services,<strong>Responsibility:</strong>\n<li>Deliver ...,NaN
12,li-4362573065,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,AI Engineer,Gulf Development Public Company Limited,https://th.linkedin.com/company/gulf-developme...,2 weeks ago,196 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,...,https://th.linkedin.com/company/gulf-developme...,2 weeks ago,198 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,Full-time,Information Technology,Holding Companies,<strong>Job Responsibilities</strong>\n1) End-...,NaN
13,li-4257267590,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Business Intelligence (Monee),Monee,https://sg.linkedin.com/company/moneehq?trk=pu...,1 week ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Entry level,...,https://sg.linkedin.com/company/moneehq?trk=pu...,1 week ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,Business Development and Sales,Financial Services,<strong>Job Description</strong>\n<li>Develop ...,NaN
14,li-4330856087,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Data Operations Analyst (Fresh Graduate Welcome),NielsenIQ,https://www.linkedin.com/company/nielseniq?trk...,1 week ago,114 applicants,Bangkok Metropolitan Area,Mid-Senior level,...,https://www.linkedin.com/company/nielseniq?trk...,1 week ago,114 applicants,Bangkok Metropolitan Area,Mid-Senior level,Full-time,General Business,Market Research,<strong>Job Description</strong>\nThe Data Pro...,NaN
15,li-4356161496,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,"(NEW GRAD ONLY) Professional, Information Tech...",WD,https://www.linkedin.com/company/western-digit...,1 week ago,Be among the first 25 applicants,"Ayutthaya, Phra Nakhon Si Ayutthaya, Thailand",Entry level,...,https://www.linkedin.com/company/western-digit...,1 week ago,Be among the first 25 applicants,"Ayutthaya, Phra Nakhon Si Ayutthaya, Thailand",Entry level,Full-time,Manufacturing,"Computer Hardware Manufacturing, Computers and...","At Western Digital, our vision is to power glo...",NaN
16,li-4354122316,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,AI Engineer,ASSETWISE PLC,https://th.linkedin.com/company/assetwise-publ...,2 weeks ago,152 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,...,https://th.linkedin.com/company/assetwise-publ...,2 weeks ago,153 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,Full-time,Information Technology,Real Estate,<strong>Overview</strong>\nWe are looking for ...,NaN
17,li-4369603049,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Data Scientist / Data Analyst,TPCS Public Company Limited,https://th.linkedin.com/company/tpcsplc?trk=pu...,NaN,Be among the first 25 applicants,"Bangkok, Bangkok City, Thailand",Entry level,...,https://th.linkedin.com/company/tpcsplc?trk=pu...,6 hours ago,Be among the first 25 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,Engineering and Information Technology,Investment Management,<strong>Job Summary</strong>\nวิเคราะห์และพัฒน...,NaN
18,li-4365580347,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,"Database Sales Specialist, Google Cloud",Google,https://www.linkedin.com/company/google?trk=pu...,1 week ago,27 applicants,"Bangkok, Bangkok City, Thailand",Not Applicable,...,https://www.linkedin.com/company/google?trk=pu...,1 week ago,27 applicants,"Bangkok, Bangkok City, Thailand",Not Applicable,Full-time,"Sales, General Business, and Customer Service","Information Services and Technology, Informati...",For Singapore Applicants:\nGoogle will be prio...,NaN
19,li-4347827427,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,"Regional Solutions Architect, Tech Solutions (...",Igloo,https://sg.linkedin.com/company/iglooinsure?tr...,3 months ago,Be among the first 25 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,...,https://sg.linkedin.com/company/iglooinsure?tr...,3 months ago,Be among the first 25 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,Full-time,Engineering and Information Technology,Non-profit Organizations and Primary and Secon...,<strong>About Igloo </strong>\nIgloo (formerly...,NaN
20,li-4365038782,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Specialists in Data Analysis,NTU International A/S,https://dk.linkedin.com/company/ntu-internatio...,2 weeks ago,84 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,...,https://dk.linkedin.com/company/ntu-internatio...,2 weeks ago,84 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,Part-time,"Consulting, Analyst, and Research",International Affairs,"<strong>Specialists in Data Analysis (Cat. I, ...",NaN
21,li-4090321977,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Data Management & Analytics (All level),ABeam Consulting Thailand,https://th.linkedin.com/company/abeam-consulti...,1 week ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,...,https://th.linkedin.com/company/abeam-consulti...,1 week ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,Full-time,Information Technology,Business Consulting and Services,<strong>About The Company</strong>\n<strong> A...,NaN
22,li-4321406975,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,"Software Engineer, Generative AI",ArcFusion,https://th.linkedin.com/company/arcfusion?trk=...,1 week ago,93 applicants,"Bangkok City, Thailand",Entry level,...,https://th.linkedin.com/company/arcfusion?trk=...,1 week ago,93 applicants,"Bangkok City, Thailand",Entry level,Full-time,Engineering and Information Technology,"Technology, Information and Internet",<strong>Come grow with us at the frontier of A...,NaN
23,li-4330730094,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,"Data Scientist - Bangsue-based, SCGP",SCG,https://th.linkedin.com/company/scg_2?trk=publ...,4 weeks ago,189 applicants,"Bang Sue, Bangkok City, Thailand",Associate,...,https://th.linkedin.com/company/scg_2?trk=publ...,4 weeks ago,189 applicants,"Bang Sue, Bangkok City, Thailand",Associate,Full-time,Information Technology,Packaging and Containers Manufacturing,<strong>Job Summary:</strong>\nYou will work a...,NaN
24,li-4182560707,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Leave Resume Here (Finance & Investment),SCG,https://th.linkedin.com/company/scg_2?trk=publ...,9 months ago,Over 200 applicants,"Bangkok City, Thailand",Entry level,...,https://th.linkedin.com/company/scg_2?trk=publ...,9 months ago,Over 200 applicants,"Bangkok City, Thailand",Entry level,Full-time,"Finance, Strategy/Planning, and Business Devel...","Chemical Manufacturing, Packaging and Containe...","Finance & Investment at SCG – Driving Growth, ...",NaN
25,li-4151310784,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,QA Engineer. (Manual),7Solutions Company Limited,https://th.linkedin.com/company/7solutions-co-...,11 months ago,Over 200 applicants,"Khlong Toei, Bangkok City, Thailand",Entry level,...,https://th.linkedin.com/company/7solutions-co-...,11 months ago,Over 200 applicants,"Khlong Toei, Bangkok City, Thailand",Entry level,Full-time,Engineering and Information Technology,Software Development,<strong>Responsibilities</strong>\n<li>Activel...,NaN
26,li-4295886471,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Business Analyst (Junior and Senior Level),Gentlewoman,https://th.linkedin.com/company/gentlewomansto...,4 months ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,...,https://th.linkedin.com/company/gentlewomansto...,4 months ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,Full-time,"Research, Analyst, and Information Technology",Retail Apparel and Fashion,<strong>Job Descriptions</strong>\n<li> Produc...,NaN
27,li-4331105655,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,IT/OT Solution Consultant,OMRON Group,https://jp.linkedin.com/company/omron-corporat...,3 months ago,Be among the first 25 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,...,https://jp.linkedin.com/company/omron-corporat...,3 months ago,Be among the first 25 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,Full-time,Information Technology,IT Services and IT Consulting,You will be responsible for technical consulti...,NaN
28,li-4292332776,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Collections Data Analyst (Monee),Monee,https://sg.linkedin.com/company/moneehq?trk=pu...,1 week ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Entry level,...,https://sg.linkedin.com/company/moneehq?trk=pu...,1 week ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,Information Technology,Financial Services,<strong>About The Team</strong>\nWe are lookin...,NaN
29,li-4334019878,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Data Insights Analyst,VML MAP,https://dk.linkedin.com/company/vml-map?trk=pu...,3 months ago,97 applicants,"Bangkok, Bangkok City, Thailand",Entry level,...,https://dk.linkedin.com/company/vml-map?trk=pu...,3 months ago,97 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,"Research, Analyst, and Information Technology",Business Consulting and Services,<li>Please note that this job is a full-time p...,NaN
30,li-4357605049,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Data Scientist (AI),ttb bank,https://th.linkedin.com/company/ttbbankofficia...,2 weeks ago,145 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,...,https://th.linkedin.com/company/ttbbankofficia...,2 weeks ago,145 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,Full-time,Information Technology,Banking,<strong>Job Summary: </strong>\nResponsible fo...,NaN
31,li-4351878509,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,TH People Team - Fresh Graduate,Shopee,https://sg.linkedin.com/company/shopee?trk=pub...,2 days ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Entry level,...,https://sg.linkedin.com/company/shopee?trk=pub...,2 days ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,Human Resources,"Internet Marketplace Platforms and Technology,...",<strong>About The Team</strong>\n<strong>Ready...,NaN
32,li-4238180562,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Marketing Analytics (Monee),Monee,https://sg.linkedin.com/company/moneehq?trk=pu...,2 weeks ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Entry level,...,https://sg.linkedin.com/company/moneehq?trk=pu...,2 weeks ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,Marketing and Sales,Financial Services,<strong>Job Description</strong>\n<li>Manage e...,NaN
33,li-4368094924,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Finance Operations - Reconciliation (ShopeePay),Shopee,https://sg.linkedin.com/company/shopee?trk=pub...,2 days ago,35 applicants,"Bangkok, Bangkok City, Thailand",Entry level,...,https://sg.linkedin.com/company/shopee?trk=pub...,2 days ago,37 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,Other,Financial Services,<strong>Job Description</strong>\n<li>Perform ...,NaN
34,li-4354813679,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Tech Solution Analyst,Publicis Groupe Thailand,https://th.linkedin.com/company/publicis-group...,3 weeks ago,91 applicants,"Bangkok City, Thailand",Entry level,...,https://th.linkedin.com/company/publicis-group...,3 weeks ago,91 applicants,"Bangkok City, Thailand",Entry level,Full-time,"Analyst, Project Management, and Information T...",Advertising Services,<strong>Overview </strong>\nThis role supports...,NaN
35,li-4177421721,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Paid Media Specialist (Ads Optimizer),Collective Hospitality,https://www.linkedin.com/company/collective-ho...,11 months ago,92 applicants,"Bangkok, Bangkok City, Thailand",Entry level,...,https://www.linkedin.com/company/collective-ho...,11 months ago,92 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,"Marketing, Public Relations, and Writing/Editing",Hospitality,<strong>About Collective Hospitality</strong>\...,NaN
36,li-4177421721,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,Paid Media Specialist (Ads Optimizer),Collective Hospitality,https://www.linkedin.com/company/collective-ho...,11 months ago,92 applicants,"Bangkok, Bangkok City, Thailand",Entry level,...,https://www.linkedin.com/company/collective-ho...,11 months ago,92 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,"Marketing, Public Relations, and Writing/Editing",Hospitality,<strong>About Collective Hospitality</strong>\...,NaN
37,li-4353957817,linkedin,https://www.linkedin.com/jobs-guest/jobs/api/j...,"Data Scientist, Makro CDC",Makro PRO,https://th.linkedin.com/company/makropro?trk=p...,2 weeks ago,Be among the first 25 applicants,"Ayutthaya, Phra Nakhon Si Ayutthaya, Thailand",Mid-Senior level,...,https://th.linkedin.com/company/makropro?trk=p...,2 weeks ago,Be among the first 25 applicants,"Ayutthaya, Phra Nakhon Si Ayutthaya, Thailand",Mid-Senior level,Full-time,Engineering and Information Technology,Retail,<strong>Requirements</strong>\n<li>Proficiency...,NaN