In [2]:
import pandas as pd
from datetime import datetime

In [3]:
file = '2026-03-12T225110'
df = pd.read_csv(f"../raw/linkedin/{file}.csv")
df.head()

,job_id,job_website,search_keyword,job_url,job_title,company_name,company_url,time_posted,num_applicants,location,seniority_level,employment_type,job_function,industries,job_description
0,li-4262353945,linkedin,Data Engineer,https://www.linkedin.com/jobs-guest/jobs/api/j...,Business Intelligence (Shopee) Fresh Graduate,Shopee,https://sg.linkedin.com/company/shopee?trk=pub...,2 weeks ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,Full-time,"Strategy/Planning, Analyst, and Consulting","Internet Marketplace Platforms and Technology,...",<strong>Job Description</strong>\n<li>Developi...
1,li-4300405780,linkedin,Data Engineer,https://www.linkedin.com/jobs-guest/jobs/api/j...,[TH] Business Intelligence - Fresh Graduate,Shopee,https://sg.linkedin.com/company/shopee?trk=pub...,6 days ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,"Strategy/Planning, Analyst, and Consulting","Internet Marketplace Platforms and Technology,...",<strong>About The Team</strong>\nThe \n<strong...
2,li-4383911083,linkedin,Data Engineer,https://www.linkedin.com/jobs-guest/jobs/api/j...,Data Engineer,Siam Digital Lending,https://th.linkedin.com/company/siamdigitallen...,2 hours ago,Be among the first 25 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,Information Technology,Financial Services,<strong>ABOUT THE ROLE</strong>\nData Engineer...
3,li-4258294987,linkedin,Data Engineer,https://www.linkedin.com/jobs-guest/jobs/api/j...,Data Engineer,Pandora,https://dk.linkedin.com/company/pandora-a-s?tr...,5 hours ago,Over 200 applicants,"Bangkok City, Thailand",Not Applicable,Full-time,"Information Technology, Product Management, an...",Retail Luxury Goods and Jewelry,Imagine being responsible for \n<strong>collab...
4,li-4383498982,linkedin,Data Engineer,https://www.linkedin.com/jobs-guest/jobs/api/j...,Data Analyst (Mid-Level),Cube,https://sg.linkedin.com/company/cube-ecom?trk=...,3 weeks ago,Be among the first 25 applicants,"Bangkok, Bangkok City, Thailand",Associate,Full-time,Analyst,IT Services and IT Consulting,<strong>This is a hybrid role based in our Ban...

In [4]:
# and more column scaling but bring the date from the file name
# timestamp form ex. YYYY-MM-DD HH:MM:SS
timestamp = file.replace('T', ' ')
timestamp = datetime.strptime(timestamp, '%Y-%m-%d %H%M%S')
print(f"Timestamp from file name: {timestamp}")

Timestamp from file name: 2026-03-12 22:51:10

In [5]:
df['scraped_at'] = timestamp

In [6]:
df.head()

,job_id,job_website,search_keyword,job_url,job_title,company_name,company_url,time_posted,num_applicants,location,seniority_level,employment_type,job_function,industries,job_description,scraped_at
0,li-4262353945,linkedin,Data Engineer,https://www.linkedin.com/jobs-guest/jobs/api/j...,Business Intelligence (Shopee) Fresh Graduate,Shopee,https://sg.linkedin.com/company/shopee?trk=pub...,2 weeks ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Mid-Senior level,Full-time,"Strategy/Planning, Analyst, and Consulting","Internet Marketplace Platforms and Technology,...",<strong>Job Description</strong>\n<li>Developi...,2026-03-12 22:51:10
1,li-4300405780,linkedin,Data Engineer,https://www.linkedin.com/jobs-guest/jobs/api/j...,[TH] Business Intelligence - Fresh Graduate,Shopee,https://sg.linkedin.com/company/shopee?trk=pub...,6 days ago,Over 200 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,"Strategy/Planning, Analyst, and Consulting","Internet Marketplace Platforms and Technology,...",<strong>About The Team</strong>\nThe \n<strong...,2026-03-12 22:51:10
2,li-4383911083,linkedin,Data Engineer,https://www.linkedin.com/jobs-guest/jobs/api/j...,Data Engineer,Siam Digital Lending,https://th.linkedin.com/company/siamdigitallen...,2 hours ago,Be among the first 25 applicants,"Bangkok, Bangkok City, Thailand",Entry level,Full-time,Information Technology,Financial Services,<strong>ABOUT THE ROLE</strong>\nData Engineer...,2026-03-12 22:51:10
3,li-4258294987,linkedin,Data Engineer,https://www.linkedin.com/jobs-guest/jobs/api/j...,Data Engineer,Pandora,https://dk.linkedin.com/company/pandora-a-s?tr...,5 hours ago,Over 200 applicants,"Bangkok City, Thailand",Not Applicable,Full-time,"Information Technology, Product Management, an...",Retail Luxury Goods and Jewelry,Imagine being responsible for \n<strong>collab...,2026-03-12 22:51:10
4,li-4383498982,linkedin,Data Engineer,https://www.linkedin.com/jobs-guest/jobs/api/j...,Data Analyst (Mid-Level),Cube,https://sg.linkedin.com/company/cube-ecom?trk=...,3 weeks ago,Be among the first 25 applicants,"Bangkok, Bangkok City, Thailand",Associate,Full-time,Analyst,IT Services and IT Consulting,<strong>This is a hybrid role based in our Ban...,2026-03-12 22:51:10

In [7]:
datetime.now()

datetime.datetime(2026, 3, 19, 2, 23, 56, 803024)

In [8]:
#save to csv and json
df.to_json(f"../raw/linkedin/{file}.json", orient="records", lines=True)
df.to_csv(f"../raw/linkedin/{file}.csv", index=False)